services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: user-service:latest
    env_file:
      - ./user-service/.env.docker

  link-service:
    build:
      context: .
      dockerfile: link-service/Dockerfile
    image: link-service:latest
    env_file:
      - ./link-service/.env.docker

  nginx:
    image: nginx:1.28
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - link-service